services:
  - type: web
    name: brickdash
    runtime: python
    buildCommand: pip install -r requirements.txt && python db.py
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SUPABASE_DB_URL
        sync: false
      - key: DB_BACKEND
        value: postgres
